/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CustomerQuery = IDL.Record({
  'resolved' : IDL.Bool,
  'question' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const ShopOpening = IDL.Record({
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBakingTip' : IDL.Func([IDL.Text], [], []),
  'addTestimonial' : IDL.Func([IDL.Text], [], []),
  'getAllCustomerQueries' : IDL.Func([], [IDL.Vec(CustomerQuery)], ['query']),
  'getBakingTips' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getShopOpenings' : IDL.Func([], [IDL.Vec(ShopOpening)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'submitCustomerQuery' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CustomerQuery = IDL.Record({
    'resolved' : IDL.Bool,
    'question' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ShopOpening = IDL.Record({
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addBakingTip' : IDL.Func([IDL.Text], [], []),
    'addTestimonial' : IDL.Func([IDL.Text], [], []),
    'getAllCustomerQueries' : IDL.Func([], [IDL.Vec(CustomerQuery)], ['query']),
    'getBakingTips' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getShopOpenings' : IDL.Func([], [IDL.Vec(ShopOpening)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'submitCustomerQuery' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };